name: cd/deploy-ecr-lambda-job-checker

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "ci/unit-tests" ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  actions: write

env:
  ECR_REPOSITORY_JOB_CHECKER: hackathon-job-checker

jobs:
  build-and-push:
    name: CD - Deploy Lambda Job Checker to ECR
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    permissions:
      contents: read
      id-token: write
    
    outputs:
      image-uri: ${{ steps.output.outputs.image-uri }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'


      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run build
        run: npm run build

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME_VIDEO_MANAGER }}/ \
            --delete \
            --exclude '.git/*' \
            --acl public-read
